# Generated by Django 3.0 on 2019-12-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDataExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'my_data_excel',
            },
        ),
        migrations.CreateModel(
            name='MyFileExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='upload/')),
            ],
            options={
                'db_table': 'my_file_excel',
            },
        ),
    ]
